plan_plan:
    resource: "@PlanBundle/Resources/config/routing/plan.yml"
    prefix:   /plan
Find_Filter:
    path:     /Find
    defaults: { _controller: "PlanBundle:Plan:RechercheFilter" }
plan_Filter_Gaspage:
    path:     /filterGas
    defaults: { _controller: PlanBundle:Plan:FilterGastronomie }
plan_Filter_Divpage:
    path:     /FilterDiv
    defaults: { _controller: PlanBundle:Plan:FilterDivertissement}
plan_FilterBE:
    path:     /filterBe
    defaults: { _controller: PlanBundle:Plan:FilterBE}

plan_FilterDIVHorizontale:
    path:     /FilterDivHorizontal
    defaults: { _controller: PlanBundle:Plan:DivertissementFilterHorizontalePage}

plan_FilterGasHorizontale:
    path:     /FilterGasHorizontal
    defaults: { _controller: PlanBundle:Plan:GastronomieFilterHorizontalePage}

plan_FilterBEHorizontale:
    path:     /FilterBEHorizontal
    defaults: { _controller: PlanBundle:Plan:BEFilterHorizontalePage}
delete_Profil:
    path:     /delete/{idP}
    defaults: { _controller: PlanBundle:Default:delete3}