services:
#    plan.example:
#        class: PlanBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
    brochures_directory: '%kernel.project_dir%/web/uploads/ImagesPlans'