hebergement_index:
    path:     /
    defaults: { _controller: "HebergementBundle:Hebergement:index" }
    methods:  GET

hebergement_show:
    path:     /{id}/show
    defaults: { _controller: "HebergementBundle:Hebergement:show" }
    methods:  GET

hebergement_new:
    path:     /new
    defaults: { _controller: "HebergementBundle:Hebergement:new" }
    methods:  [GET, POST]

hebergement_edit:
    path:     /{id}/edit
    defaults: { _controller: "HebergementBundle:Hebergement:edit" }
    methods:  [GET, POST]

hebergement_delete:
    path:     /{id}/delete
    defaults: { _controller: "HebergementBundle:Hebergement:delete" }
    methods:  DELETE

hotels_index:
    path:     /hotels
    defaults: { _controller: "HebergementBundle:Hebergement:indexhotels" }
    methods:  GET

maisons_index:
    path:     /maisons
    defaults: { _controller: "HebergementBundle:Hebergement:indexmaisons" }
    methods:  GET

pensions_index:
    path:     /pensions
    defaults: { _controller: "HebergementBundle:Hebergement:indexpensions" }
    methods:  GET


recherchebyregion:
    path:     /{name}/rech
    defaults: { _controller: "HebergementBundle:Hebergement:rech" }
    methods:  GET


rechprix:
    path:     /maxprix
    defaults: { _controller: "HebergementBundle:Hebergement:rech2" }
    methods:  GET


esp:
    path:     /esp
    defaults: { _controller: "HebergementBundle:Hebergement:esp" }
    methods:  GET

mesbonplan:
    path:     /mesbonplan
    defaults: { _controller: "HebergementBundle:Hebergement:mesbonplan" }
    methods:  GET
hebergement_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "HebergementBundle:Hebergement:pdf" }
    methods:  GET

hebergement_conf:
    path:     /{id}/conf
    defaults: { _controller: "HebergementBundle:Hebergement:conf" }
    methods:  GET


rechadmin:
    path:     /rechadmin
    defaults: { _controller: "HebergementBundle:Hebergement:rechadmin" }
    methods:  POST

hebergement_allM:
    path:     /all
    defaults: { _controller: "HebergementBundle:Hebergement:all" }

hebergement_findM:
    path:     /find/{id}
    defaults: { _controller: "HebergementBundle:Hebergement:find" }

hebergement_ajoutM:
    path:     /newM
    defaults: { _controller: "HebergementBundle:Hebergement:WSnew" }

hebergement_suppM:
    path:     /{id}/deleteM
    defaults: { _controller: "HebergementBundle:Hebergement:WSdelete" }

hebergement_map:
    path:     /map
    defaults: { _controller: "HebergementBundle:Hebergement:map" }

hebergement_image:
    path:     /image
    defaults: { _controller: "HebergementBundle:Hebergement:uploadImage" }