messagerie_index:
    path:     /
    defaults: { _controller: "HebergementBundle:Messagerie:index" }
    methods:  GET

messagerie_show:
    path:     /{id}/show
    defaults: { _controller: "HebergementBundle:Messagerie:show" }
    methods:  GET

messagerie_new:
    path:     /{idh}/new
    defaults: { _controller: "HebergementBundle:Messagerie:new" }
    methods:  [GET, POST]

messagerie_edit:
    path:     /{id}/edit
    defaults: { _controller: "HebergementBundle:Messagerie:edit" }
    methods:  [GET, POST]

messagerie_delete:
    path:     /{id}/delete
    defaults: { _controller: "HebergementBundle:Messagerie:delete" }
    methods:  GET

messagerie_indexAdmin:
    path:     /
    defaults: { _controller: "HebergementBundle:Messagerie:indexAdmin" }
    methods:  GET

messagerie_ajoutM:
    path:     /newMessaMob
    defaults: { _controller: "HebergementBundle:Messagerie:WSnewMess" }

messagerie_editM:
    path:     /{id}/editM
    defaults: { _controller: "HebergementBundle:Messagerie:editM" }

messagerie_showM:
    path:     /all
    defaults: { _controller: "HebergementBundle:Messagerie:all" }