ReviewBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: ReviewBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            type: integer
            column: id_user
        idPlan:
            type: integer
            column: id_plan
        contenu:
            type: string
            length: '150'
    lifecycleCallbacks: {  }
