article_index:
    path:     /
    defaults: { _controller: "PubliciteBundle:Article:index" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "PubliciteBundle:Article:show" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "PubliciteBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "PubliciteBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "PubliciteBundle:Article:delete" }
    methods:  [GET, POST]

article_indexPerso:
    path:     /perso
    defaults: { _controller: "PubliciteBundle:Article:indexPerso" }
    methods:  GET

recherche_article:
    path:     /chercherArticle
    defaults: { _controller: "PubliciteBundle:Article:chercher" }
