<?php

namespace PubliciteBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    public function AVGRating()
    {
        $query = $this->getEntityManager()
            ->createQuery("select c.publicite, AVG (c.rating) from 
         PubliciteBundle:rating c GROUP BY c.publicite"
            );
        return $query->getResult();
    }

    public function Trend()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM
                      PubliciteBundle:Publicite c 
                      ORDER BY c.nbClick DESC "
            );
        return $query->getResult();
    }
}






