<?php

namespace PlanBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    public function AVGRating()
    {
        $query = $this->getEntityManager()
            ->createQuery("select c.plan, AVG (c.rating) from 
         PlanBundle:Rating c GROUP BY c.plan"
            );
        return $query->getResult();
    }
}






