back_office_homepage:
    path:     /admin
    defaults: { _controller: BackOfficeBundle:Default:index }

layout:
    path:     /layout
    defaults: { _controller: BackOfficeBundle:Default:layout }

widget:
    path:     /widget
    defaults: { _controller: BackOfficeBundle:Default:widget}

chart:
    path:     /chart
    defaults: { _controller: BackOfficeBundle:Default:chart }
table:
    path:     /table
    defaults: { _controller: BackOfficeBundle:Default:table }
form:
    path:     /form
    defaults: { _controller: BackOfficeBundle:Default:form }
panel:
    path:     /panel
    defaults: { _controller: BackOfficeBundle:Default:panel }
icon:
    path:     /icon
    defaults: { _controller: BackOfficeBundle:Default:icon }
plan_indextableau:
    path:     /AffP
    defaults: { _controller: BackOfficeBundle:PlanBackOff:AllPlansBack  }
    methods:  [GET, POST]
plan_valider:
    path:     /{idP}/val
    defaults: { _controller: BackOfficeBundle:PlanBackOff:ValiderPlan  }
plan_Nonvalide:
    path:     /{idP}/NonVal
    defaults: { _controller: BackOfficeBundle:PlanBackOff:NonValidePlan  }
New_PlanBack:
    path:     /new
    defaults: { _controller: BackOfficeBundle:PlanBackOff:AjouterPlanBack  }

demandePub:
    path:     /demandePub
    defaults: { _controller: BackOfficeBundle:PubBack:index  }
    methods:  [GET, POST]

validPub:
    path:     /{idPub}/validePub
    defaults: { _controller: BackOfficeBundle:PubBack:valider }
    methods:  [GET, POST]

refusPub:
    path:     /{idPub}/refusPub
    defaults: { _controller: BackOfficeBundle:PubBack:refuser }
    methods:  [GET, POST]

demandeArticle:
    path:     /demandeArticle
    defaults: { _controller: BackOfficeBundle:ArticleBack:index  }
    methods:  [GET, POST]

validArticle:
    path:     /{id}/valideArticle
    defaults: { _controller: BackOfficeBundle:ArticleBack:valider }
    methods:  [GET, POST]

refusArticle:
    path:     /{id}/refusArticle
    defaults: { _controller: BackOfficeBundle:ArticleBack:refuser }
    methods:  [GET, POST]
gestionplan:
    path:     /gestion
    defaults: { _controller: BackOfficeBundle:PlanBackOff:gestion}
    methods:  [GET, POST]
listeplan:
    path:     /liste
    defaults: { _controller: BackOfficeBundle:PlanBackOff:AllPlans}
    methods:  [GET, POST]
StatistiqueGlobale:
    path:     /statisqtiqueG
    defaults: { _controller: BackOfficeBundle:PlanBackOff:StatiqtiquesAllPlans}
    methods:  [GET, POST]

tousutilisat:
    path:     /tousutilisat
    defaults: { _controller: BackOfficeBundle:Signal:index  }
    methods:  [GET, POST]

signalutilisat:
    path:     /signalutilisat
    defaults: { _controller: BackOfficeBundle:Signal:index2  }
    methods:  [GET, POST]

validuser:
    path:     /{id}/valideuser
    defaults: { _controller: BackOfficeBundle:Signal:valider }
    methods:  [GET, POST]

refususer:
    path:     /{id}/refususer
    defaults: { _controller: BackOfficeBundle:Signal:refuser }
    methods:  [GET, POST]

bloquerutilisat:
    path:     /bloquerutilisat
    defaults: { _controller: BackOfficeBundle:Signal:index3  }
    methods:  [GET, POST]

valid2user:
    path:     /{id}/valide2user
    defaults: { _controller: BackOfficeBundle:Signal:valider2 }
    methods:  [GET, POST]

validusertous:
    path:     /{id}/validetoususer
    defaults: { _controller: BackOfficeBundle:Signal:validertous }
    methods:  [GET, POST]

refususertous:
    path:     /{id}/refustoususer
    defaults: { _controller: BackOfficeBundle:Signal:refusertous }
    methods:  [GET, POST]