<?php

namespace ReviewBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function commentidommarDQL($id){

        $req=$this->getEntityManager()->createQuery("SELECT c FROM
                      PiBundle:User c JOIN 
                      PlanBundle:Plan r WHERE c.id = r.user and r.idP=:p")
            ->setParameter('p',$id);

        return $req->getResult();


    }



}
