<?php

namespace ReviewBundle\Repository;

/**
 * SignaisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignaisationRepository extends \Doctrine\ORM\EntityRepository
{
}
