review_commentaire:
    resource: "@ReviewBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire

commentaire_ajout:
    path:     /ajoutcom
    defaults: { _controller: "ReviewBundle:Commentaireomar:ajoutercom" }
